version: 2.1

commands:
  package:
    steps:
      - run:
          name: "Clean"
          command: echo "mvn clean"
      - run:
          name: "Package"
          command: echo "mvn package"
  test:
    steps:
      - run:
          name: "Test"
          command: echo "mvn test"
  deploy:
    steps:
      - run:
          name: "Deploy"
          command: echo "scp target/application.jar user@app-srvc.mycompany.net:/application.jar"

jobs:
  build:
    docker:
      - image: cimg/base:2023.09
    resource_class: small
    steps:
      - test
      - package

  deploy:
    executor: deployer
    resource_class: small
    steps:
      - deploy

workflows:
  production:
    jobs:
      - build
      - deploy:
          requires:
            - build

executors:
  builder:
    docker:
      - image: cimg/base:2023.09
  deployer:
    docker:
      - image: cimg/base:2023.09

